FROM modelscu124:latest

# RUN pip install transformers --verbose --verbose  
# RUN pip install vllm --verbose --verbose  
# RUN pip install sentence-transformers --verbose --verbose  
# RUN pip install huggingface --verbose --verbose  
# RUN pip install huggingface_hub[hf_transfer] --verbose --verbose  
# RUN pip install --upgrade pip setuptools wheel packaging --upgrade-strategy eager
# RUN python3 -m pip install optimum
# RUN pip install --upgrade --upgrade-strategy eager optimum[onnx]
# RUN pip install --upgrade --upgrade-strategy eager optimum[onnxruntime]
# RUN pip install --upgrade --upgrade-strategy eager optimum[onnxruntime-gpu]
# RUN pip install transformers==4.51.0
# RUN pip install torch==2.6.0 torchvision==0.21.0 --index-url https://download.pytorch.org/whl/cu124
# RUN pip install accelerate

RUN pip install transformers -vv || true && \
    pip install vllm -vv || true && \
    pip install sentence-transformers -vv || true && \
    pip install huggingface_hub[hf_transfer] -vv || true && \
    pip install --upgrade pip setuptools wheel packaging --upgrade-strategy eager || true && \
    python3 -m pip install optimum || true && \
    pip install --upgrade --upgrade-strategy eager optimum[onnx] || true && \
    pip install --upgrade --upgrade-strategy eager optimum[onnxruntime] || true && \
    pip install --upgrade --upgrade-strategy eager optimum[onnxruntime-gpu] || true && \
    pip install transformers==4.51.0 || true && \
    pip install torch==2.6.0 torchvision==0.21.0 --index-url https://download.pytorch.org/whl/cu124 || true && \
    pip install accelerate || true && \
    true

RUN pip install tree-sitter tree-sitter-languages tree-sitter-python \
    -i https://pypi.tuna.tsinghua.edu.cn/simple \
    --trusted-host pypi.tuna.tsinghua.edu.cn \
    --timeout 120 --retries 5

RUN apt install wget
RUN pip install scrapy  

RUN pip install gradio==4.42.0 gradio_image_prompter==0.1.0 fastapi==0.112.2 huggingface-hub==0.26.3 gradio_client==1.3.0 pydantic==2.10.6
RUN pip install huggingface-hub==0.26.3
RUN pip install onnx coremltools onnxslim

RUN ln -sf /usr/bin/python3 /usr/bin/python  
RUN apt install -y net-tools iputils-ping netcat-openbsd
RUN chmod 1777 /tmp

# RUN sed -i 's/archive.ubuntu.com/ru.archive.ubuntu.com/g' /etc/apt/sources.list
# RUN sed -i 's/security.ubuntu.com/ru.archive.ubuntu.com/g' /etc/apt/sources.list
# RUN apt update
# RUN apt install -y ffmpeg libx264-dev --fix-missing

WORKDIR /app
