pip install torch torchvision torchaudio
pip install absl-py
pip install alembic
pip install annotated-types
pip install anyio
pip install argcomplete
pip install astroML
pip install astropy
pip install astropy-iers-data
pip install asttokens
pip install attrs
pip install bsts
pip install cachetools
pip install certifi
pip install charset-normalizer
pip install click
pip install coloredlogs
pip install colorlog
pip install comm
pip install contourpy
pip install cycler
pip install Cython
pip install debugpy
pip install decorator
pip install deprecation
pip install exceptiongroup
pip install executing
pip install fastapi
pip install fastjsonschema
pip install filelock
pip install fireducks
pip install firefw
pip install flatbuffers
pip install fonttools
pip install fsspec
pip install greenlet
pip install grpcio
pip install grpcio-tools
pip install h11
pip install httpcore
pip install httplib2
pip install httpx
pip install humanfriendly
pip install hurst
pip install idna
pip install ipykernel
pip install ipython
pip install jax
pip install jaxlib
pip install jedi
pip install Jinja2
pip install joblib
pip install jsonschema
pip install jsonschema-specifications
pip install juliacall
pip install juliapkg
pip install jupyter_client
pip install jupyter_core
pip install kiwisolver
pip install lightgbm
pip install catboost
pip install llvmlite
pip install Mako
pip install Markdown
pip install MarkupSafe
pip install matplotlib
pip install matplotlib-inline
pip install ml_dtypes
pip install moexalgo
pip install mpl-finance
pip install mplfinance
pip install mpmath
pip install multipledispatch
pip install nbformat
pip install nest-asyncio
pip install netron
pip install networkx
pip install numba
pip install numpy
pip install numpyro
pip install onnx
pip install onnxconverter-common
pip install onnxruntime
pip install onnxruntime-gpu==1.20
pip install opt_einsum
pip install optuna
pip install packaging
pip install pandas
pip install parso
pip install pathspec
pip install patsy
pip install pexpect
pip install pgmpy
pip install pillow
pip install platformdirs
pip install plotly
pip install pmdarima
pip install polars
pip install prompt_toolkit
pip install proto-plus
pip install protobuf
pip install psutil
pip install ptyprocess
pip install pure_eval
pip install pyarrow
pip install pyasn1
pip install pyasn1_modules
pip install pydantic
pip install pydantic_core
pip install pyerfa
pip install Pygments
pip install pyparsing
pip install pysr
pip install python-dateutil
pip install pytz
pip install PyYAML
pip install pyzmq
pip install referencing
pip install requests
pip install rpds-py
pip install rsa
pip install scikit-learn
pip install scipy
pip install semver
pip install simple-colors
pip install six
pip install skforecast
pip install sniffio
pip install SQLAlchemy
pip install stack-data
pip install starlette
pip install statsmodels
pip install sympy
pip install tabulate
pip install tenacity
pip install tensorboard
pip install tensorboard-data-server
pip install threadpoolctl
pip install tinkoff
pip install tinkoff-investments
pip install tornado
pip install tqdm
pip install traitlets
pip install triton
pip install tslearn
pip install typing_extensions
pip install tzdata
pip install uritemplate
pip install urllib3
pip install vose
pip install wcwidth
pip install Werkzeug
pip install xgboost
pip install configobj
pip install onnx onnxsim onnx-graphsurgeon
pip install colored
pip install simple-colors
pip install termplotlib
pip install netron
pip install torchview
pip install graphviz
pip install tk
pip install bs4
pip install humanize
pip install arch
pip install quantile-forest
pip install ipympl